### ISSUE TITLE
Readme fix

### ISSUE THREAD

**Issue by LSB-dev** [YassineHimeur/QUD-dataset#1]
Hi there,
we're a research group from Germany currently working with your dataset. 
We just wanted to let you know, that there's a typo in your readme, which do mess up the classes:

Your text:
“class 0: good usage”, “class 1: turn on”, and “class 2: turn off”. On the other hand, “class 4: excessive power consumption” and “class 5: consumption when outside” describe anomalous consumption.

The labels according to your paper's description:
“class 0: good usage”, “class 1: turn on”, and “class 2: turn off”. On the other hand, “class **3**: excessive power consumption” and “class **4**: consumption when outside” describe anomalous consumption.

Btw, thanks for sharing this data.

**Comment by abdol** [comment]
Thank you for the heads up. README.md has been corrected accordingly.
